# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{uri_handler}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["msalzburg", "mherold"]
  s.date = %q{2010-08-31}
  s.description = %q{longer description of your gem}
  s.email = %q{admin@emjot.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".yardoc/checksums",
     ".yardoc/objects/URIHandler.dat",
     ".yardoc/objects/URIHandler/Base.dat",
     ".yardoc/objects/URIHandler/Base/fetch_uri_i.dat",
     ".yardoc/objects/URIHandler/Base/host_i.dat",
     ".yardoc/objects/URIHandler/Base/initialize_i.dat",
     ".yardoc/objects/URIHandler/Base/is_valid_3F_i.dat",
     ".yardoc/objects/URIHandler/Base/redirect_limit_i.dat",
     ".yardoc/objects/URIHandler/Base/redirect_log_i.dat",
     ".yardoc/objects/URIHandler/Base/redirected_3F_i.dat",
     ".yardoc/objects/URIHandler/Base/scheme_i.dat",
     ".yardoc/objects/URIHandler/Base/source_uri_i.dat",
     ".yardoc/objects/URIHandler/Base/status_i.dat",
     ".yardoc/objects/URIHandler/Base/uri_i.dat",
     ".yardoc/objects/URIHandler/Base/url_i.dat",
     ".yardoc/objects/URIHandler/Base/valid_host_3F_i.dat",
     ".yardoc/objects/URIHandler/Base/valid_hosts_i.dat",
     ".yardoc/objects/URIHandler/Base/valid_length_3F_i.dat",
     ".yardoc/objects/URIHandler/Base/valid_length_i.dat",
     ".yardoc/objects/URIHandler/Base/valid_scheme_3F_i.dat",
     ".yardoc/objects/URIHandler/Base/valid_schemes_i.dat",
     ".yardoc/objects/URIHandler/ClassMethods.dat",
     ".yardoc/objects/URIHandler/ClassMethods/acts_as_uri_i.dat",
     ".yardoc/objects/URIHandler/InstanceMethods.dat",
     ".yardoc/objects/URIHandler/InstanceMethods/build_uri_i.dat",
     ".yardoc/objects/URIHandler/Response.dat",
     ".yardoc/objects/URIHandler/Response/code_i.dat",
     ".yardoc/objects/URIHandler/Response/initialize_i.dat",
     ".yardoc/objects/URIHandler/Response/uri_i.dat",
     ".yardoc/objects/URIHandler/included_c.dat",
     ".yardoc/objects/root.dat",
     ".yardoc/proxy_types",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/uri_handler/USAGE",
     "generators/uri_handler/templates/uri_handler_migration.rb.erb",
     "generators/uri_handler/uri_handler_generator.rb",
     "init.rb",
     "lib/uri_handler.rb",
     "lib/uri_handler/base.rb",
     "lib/uri_handler/response.rb",
     "spec/lib/uri_handler/base_spec.rb",
     "spec/lib/uri_handler/response_spec.rb",
     "spec/lib/uri_handler_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/msalzburg/uri_handler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{a handsome gem to resolve uri redirects and handle uri validation within activerecord}
  s.test_files = [
    "spec/lib/uri_handler/base_spec.rb",
     "spec/lib/uri_handler/response_spec.rb",
     "spec/lib/uri_handler_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 2.3.8"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 2.3.8"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 2.3.8"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

